<?php

/* Strings (movie edition) */

/* 1. Create two variables. Assign your favorite actress's first and last names as strings. 
Print the longer string. */

/* 2. Create two variables. Assign your favorite actress's first and last names as strings. 
Print the first name in lowercase and the last name in uppercase. */

/* 3. Create two variables. Assign your favorite actress's first and last names as strings. 
Create a third variable containing the first three letters of the first name and the last 
three letters of the last name. Print this string. */

/* 4. Create a variable with the string: “Back to the Future”. 
Replace all occurrences of the letter “u” (uppercase and lowercase) with “_”. Print the result. */

/* 5. Create a variable with the string: “Back to the Future”. 
Count all the “t” (both uppercase and lowercase) letters in the string. Print the result. */

/* 6. Create a variable with the string: “Back to the Future”. 
Remove all consonants from the string and print the result. 
Repeat the code with the strings: “The Godfather”, “Pulp Fiction”, and “Forrest Gump”. */

/* 7. In a string generated by this code:
'Indiana Jones: '.str_repeat(' ', rand(0,5)). rand(1,4) . ' - Raiders of the Lost Ark';
Find and print the number after "Indiana Jones: " (the episode number).
*/

/* 8. Count how many words in the string “The Lord of the Rings: The Return of the King” are longer than 
7 letters. Repeat with the string “Pirates of the Caribbean: The Curse of the Black Pearl”. */

/* 9. Write code that generates a random string of 5 Latin uppercase letters. */

/* 10. Write code that generates a random string with 8 randomly arranged words, 
taken from the two movie titles in task 8. Words must not repeat. (Use arrays.) */

/* 11. Create a variable with the string: “Gone with the Wind”. 
Print the string in reverse order (last letter first, etc.). */

/* 12. Create two variables with two different movie titles. 
Print the number of vowels in both titles combined. */

/* 13. Create a variable with the string: “The Matrix”. 
Print only every second character of the string (starting from the first). */

/* 14. Create a variable with the string: “Casablanca”. 
Randomly shuffle all the characters and print the result. */

/* 15. Advanced. Generate a string with 12 random lowercase Latin letters.
 Print the string and the character that occurs most frequently in it. 
 If there are several, print all of them. */

/* 16. Advanced. Create a string with a movie title of your choice. 
Print the number of unique letters in the title. Ignore spaces and case. */

/* 17. Advanced. Create a variable with the string: “One Flew Over the Cuckoo’s Nest”. 
Print the string with all words sorted in alphabetical order (ignore punctuation). */

/* 18. Advanced. Create two variables with two movie titles. P
rint the combined string, but with all duplicate letters (case-insensitive) removed, 
keeping only the first occurrence. */

/* 19. Advanced. Generate a random string of 10 characters (letters and numbers). 
Print the string, and print whether it is a palindrome. */

/* 20. Advanced. Create a variable with the string: “Inception”. 
Print all possible unique two-letter combinations that can be formed from the string’s letters. */
?>